name: "Test"
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: teaconmc/dedicated-launch-test@1.18
        with:
          extra: extra.json
          mod: CannonFire-Forge-1.18-0.1.4.jar

